name = "ndrsc"
compatibility_date = "2025-02-01"

[assets]
directory = "./data_collect/NDRSC_FRONTEND/dist"

[build]
command = "cd data_collect/NDRSC_FRONTEND && npm install && npm run build"
